service: steam-battle-serverless

provider:
  name: google
  runtime: nodejs
  project: steam-battle-serverless
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/steam-battle-serverless-keyfile.json

plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  checkid:
    handler: checkid
    environment:
      STEAM_API_KEY: ${file(env.yml):STEAM_API_KEY}
    events:
      - http:
          path: checkid
          method: get
          cors: true
          request:
            paramaters:
              querystrings:
                id: true
  player:
    handler: player
    environment:
      STEAM_API_KEY: ${file(env.yml):STEAM_API_KEY}
    events:
      - http:
          path: player
          method: get
          cors: true
          request:
            paramaters:
              querystrings:
                id: true
